### ISSUE TITLE
[Feature Request] LevelledMobs Integration

### ISSUE THREAD

**Issue by FunkyNico** [JeannotM/DynamicDifficulty#8]
Hello, i was thinking that would be cool to implement LevelledMobs to the affinity points system of this plugin, so newer players recieve lower level mobs and experienced players have more challenging mobs fights against high level mobs.

I think this can be added on LevelledMobs as a custom rule preset also.

[LevelledMobs](https://github.com/lokka30/LevelledMobs)
[LevelledMobs API](https://github.com/lokka30/LevelledMobs/wiki/Developing-with-LevelledMobs)

Thanks,

**Comment by Shad0wolf0** [comment]
You can use a custom rule!
here is my example rule. the "1-5: 1-600" represents "minMobLevel-maxMobLevel: minAffinity-maxAffinity" so you can add more.
`  - enabled: true
    name: 'Dynamic Difficulty Player Affinity Rule'
#    This rule requires the soft-dependency PlaceholderAPI to function!
#    Make sure you have it installed prior to enabling this rule!
    strategies:
      player-levelling:
        match-level: true
        use-player-max-level: false
        decrease-level: true
        player-level-scale: 1.0
        level-cap: 100
        tiers:
          1-5: 1-600
        condition: '%dd_user_affinity%'`

**Comment by cjtganzon** [comment]
you can use custom rule! here is my example. needs placeholderapi. "1-600" is affinity and "1-25" is the level
```
  - enabled: true
    name: 'Dynamic Difficulty Player Affinity Rule'
    strategies:
      player-levelling:
        match-level: false
        use-player-max-level: false
        player-level-scale: 1.0
        level-cap: 30
        decrease-level: false
        recheck-players: false
        preserve-entity: 10s
        tiers:
          1-600: 1-5
        variable: '%dd_user_affinity%'
```
